config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "movie_catalog#index"
  get "search", to: "search#index", as: :search
  get "add", to: "movie_catalog#add", as: :add
  get "destroy", to: "movie_catalog#destroy", as: :destroy
  post "rate", to: "movie_catalog#rate", as: :rate
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movie_catalog_controller.rb
class MovieCatalogController < ApplicationController
    def index
        @movies = Movie.all
    end

    def add
        image = params[:image]
        name = params[:name]
        release = params[:release]
        runtime = params[:runtime]
        genres = params[:genres]
        @movie = Movie.create(image: image, name: name, release: release, runtime: runtime.to_i, genres: genres)
        redirect_to root_path
    end

    def destroy
        id = params[:id]
        Movie.destroy(id)
        redirect_to root_path
    end

    def rate
        id = params[:id]
        rating = params[:rating].to_i
        if rating >= 0 && rating <= 10
            Movie.update(id, :rating => rating)
            redirect_to root_path
        end
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    def index
        #@response = RestClient.get "https://api.themoviedb.org/3/movie/popular?api_key=d21b3a5266a4cf0deeece6c9c6782523"
        #@json = JSON.parse @response
        #if !@json.nil?
        #    @movies = @json["results"]
           # @movies.map do |movie|
                #@q = @movies.ransack(params[:q])
                #@movies = @q.result(distinct: true)
            #ransacker :original_title do |parent|
            #    Arel::Nodes::InfixOperation.new('->', parent.table[:json_column], 'phone1')
            #end
           # end
       # end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GlookoZadatak</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <!--<script src="//javascript/controllers/movie_catalog.js"></script>-->
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render partial: "shared/navbar" %>
    <div class= "container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/movie_catalog/add.html.erb
<h1>Eelements added, redirecting...</h1>

app/views/movie_catalog/destroy.html.erb
<h1>destory item</h1>

app/views/movie_catalog/index.html.erb
<style>
  .addHover :hover {
      transition: .5s ease;
      opacity: 0.7;
      background: black;
    }
</style>
<div class = "d-flex align-items-center justify-content-center">
  <h1>Movie catalog</h1>
</div>
<%= button_to "Add new movie", search_path, method: :get%>
<table id = "movies_display"></table>
<% @movies.each do |movie| %>
  <%- if movie.rating == nil %>
    <%- rating = "--" %>
  <%- else %>
    <%- rating = movie.rating %>
  <%- end %>
  <p style = "visibility: hidden;"><%= destroy_path = "http://localhost:3000/destroy?id=#{movie.id}" %></p>
  <ul class = "navbar-nav">
    <li>
      <div class="container" style = "max-width: 90%; height: auto;">
        <a href=<%= destroy_path%> class="addHover">
          <figure class="figure">
            <div class="card-img">
              <img src= <%=movie.image%> class="figure-img img-fluid rounded" alt="A" style = "pointer-events: none">
            </div>
            <figcaption class="figure-caption text-center">
              <h5> <%= movie.name %> </h5>
              <p>Rutime: <%= movie.runtime %></p>
              <p>Release: <%= movie.release %></p>
              <p>Genres: <%= movie.genres %></p>
              <p>Rating: <%= rating %> </p>
            </figcaption>
          </figure>
        </a>
      </div>
    </li>
    <li>
      <%= form_with url: rate_path, local: true, method: :post do %>
        <input name="id" style="visibility: hidden;" value =<%= movie.id%>>
        <input name="rating", placeholder="Rate(0-10)"></input>
      <button type="submit">Rate</button>
    <% end %>
  </li>
</ul>
<% end%>

app/views/search/index.html.erb
<style>
  .addHover :hover {
    transition: .5s ease;
    opacity: 0.7;
    background: black;
  }
</style>
<script>
  const DETAILS_URL = "https://api.themoviedb.org/3/movie/";
  const TMDB_API_KEY = "d21b3a5266a4cf0deeece6c9c6782523";
  const BASE_URL = "https://image.tmdb.org/t/p/w500/";
  const POPULAR_URL = "https://api.themoviedb.org/3/movie/popular?api_key="
  const SEARCH_URL = "https://api.themoviedb.org/3/search/movie?api_key="

    async function getTMDB(){
      const res = await fetch(POPULAR_URL+TMDB_API_KEY);
      const json = await res.json();
      const movies = json.results;
      return movies;
    }

    async function searchTMDB(searchMovie){
      const res = await fetch(SEARCH_URL+TMDB_API_KEY+"&query="+searchMovie);
      const json = await res.json();
      const searchRes = json.results;
      return searchRes;
    }

    async function displayMovies(movies){

      let tbl = document.getElementById("movies_display");
      tbl.innerHTML= '';

      let counter = 0;
      let container;
      for (let movie of movies) {
        if (counter % 3 == 0){
          const newRow = document.createElement('tr');
          tbl.appendChild(newRow);
        }
        container = document.createElement('td');
        counter++;

        const res = await fetch(DETAILS_URL + movie.id + "?api_key=" + TMDB_API_KEY);
        const details = await res.json();
        let image_path = "https://t3.ftcdn.net/jpg/02/48/42/64/240_F_248426448_NVKLywWqArG2ADUxDq6QprtIzsF82dMF.jpg";
        if(movie.backdrop_path != null){
          image_path ="https://image.tmdb.org/t/p/w500/" + movie.backdrop_path;
        }
        const genres = details.genres;
        let genresString = "";
        for(let i = 0; i<Object.keys(genres).length; i++){
          if(i==(Object.keys(genres).length-1)){
            genresString += genres[i].name
          }
          else{
            genresString += genres[i].name + ",";
          }
        }
        for(let i=0; i<genresString.length; i++){
          if(genresString[i] == ' '){
            genresString[i] = +'%20';
          }
        }
        for(let i=0; i<details.original_title.length; i++){
          if(details.original_title[i] == ' '){
            details.original_title[i] = +'%20';
          }
        }

        const addLink = "http://localhost:3000/add?image="+image_path+"&name="+details.original_title+"&runtime="+details.runtime+"&release="+details.release_date+"&genres="+genresString;
        let template= `
          <div class="container" style = "max-width: 90%; height: auto;">
          <a href="${addLink}" class="addHover">
            <figure class="figure">
              <div class="card-img">
                <img src="${image_path}" class="figure-img img-fluid rounded" alt="A">
              </div>
              <figcaption class="figure-caption text-center"><h5>${movie.original_title}</h5></figcaption>
            </figure>
          </a>
        </div>
          `
        container.innerHTML = template;
      tbl.appendChild(container);
      };
    }

    async function movies(){
      const movies = await getTMDB();
      displayMovies(movies);
    }

    async function handleSearch(){
      var searchTerm = document.getElementById("search").value;
      if(searchTerm.length){
        var tokens = searchTerm.split(' ');
        var searchMovie= tokens.join('+');
        const movies = await searchTMDB(searchMovie);
        displayMovies(movies);
      }
      else{
        tbl.innerHTML= '';
        movies();
      }
    }

    window.onload = movies();
</script>
<h1>Search</h1>
<nav class="navbar navbar-expand-lg sticky-top navbar-light bg-light">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" id="search">
    </li>
    <li class="nav-item active" style="margin-left: 30px;">
      <button onclick="handleSearch();">Search</button>
    </li>
  </ul>
</nav>
<table id = "movies_display"></table>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg sticky-top navbar-light bg-light">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <%= link_to "Home", root_path, class: "nav-link"%>
    </li>
    <li class="nav-item active">
      <%= link_to "Search", search_path, class: "nav-link"%>
    </li>
  </ul>
</nav>